GLOBAL_CONFIG:
  project_name: 'dataomnis'

ZONE_CONFIG:
  default:
    valid_sider_features:
      - name: dataomnis
        title: dataomnis
        portal_name: dataomnis
        en: dataomnis
        icon: project
        zh-cn: '大数据工作台'
        items:
          - {
              name: overview,
              title: Overview,
              icon: dashboard,
              zh-cn: 概览,
              en: Overview,
            }
          - {
              name: workspace,
              title: Workspace,
              icon: project,
              zh-cn: 工作空间,
              en: Workspace,
            }
