version: '3.2'
services:
  webconsole:
    image: webconsole:latest
    command: 'gunicorn --bind :8000 --workers=4 mysite.wsgi:application'
    volumes:
      - type: bind
        source: '${CONSOLE_SRC}'
        target: /pitrix/lib/pitrix-webconsole
      - type: bind
        source: '${SRC}/configs'
        target: /pitrix/lib/pitrix-webconsole/configs
      - type: bind
        source: ./web_console_settings.py
        target: /pitrix/conf/web_console_settings.py
      - type: bind
        source: ./memcached.yaml
        target: /pitrix/conf/global/memcached.yaml
    expose:
      - '8000'
    depends_on:
      - memcached
  memcached:
    image: memcached:1.6.10
    container_name: memcached
    expose:
      - '11211'
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ${SRC}
        target: /pitrix/lib/pitrix-webconsole-dataomnis
      - type: bind
        source: ${CONSOLE_SRC}/static
        target: /pitrix/lib/pitrix-webconsole/static
    ports:
      - ${NGINX_EXPOSE_PORT}:80
    depends_on:
      - webconsole
